version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3002:5173"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://api:3000
      - VITE_API_URL=http://api:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - ai-chat-network

networks:
  ai-chat-network: