version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ai_chat
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=1d
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - ai-chat-network

  mock-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./:/app
      - /app/node_modules
    command: ./node_modules/.bin/ts-node-dev --respawn --transpile-only -r tsconfig-paths/register src/mock-server.ts
    networks:
      - ai-chat-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_chat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-chat-network

networks:
  ai-chat-network:

volumes:
  postgres_data: