version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - STORAGE_TYPE=memory
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRES_IN=1d
      - LOCAL_LOGS_PATH=./mock-logs
    volumes:
      - ./:/app
      - /app/node_modules
      - ${LOCAL_LOGS_PATH:-./mock-logs}:/var/log/foundation
    command: npm run dev
    networks:
      - ai-chat-network

  mock-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    volumes:
      - ./:/app
      - /app/node_modules
    command: ./node_modules/.bin/ts-node-dev --respawn --transpile-only -r tsconfig-paths/register src/mock-server.ts
    networks:
      - ai-chat-network

networks:
  ai-chat-network:
